# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers (with system deps)
      run: npx playwright install --with-deps

    - name: Build site
      run: npm run build

    # - name: Run tests
    #   env:
    #     CI: true
    #   run: npm test

    - name: Upload Playwright report (artifact)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report
        if-no-files-found: ignore
    
    - name: Eleventy Action
      # You may pin to the exact commit or the version.
      # uses: TartanLlama/actions-eleventy@6c28b3072246fb361c537282e3eac5ab9b6ac85e
      uses: TartanLlama/actions-eleventy@v1.2
      with:
        # args: Arguments to pass to the Eleventy invocation. optional
        # If set to `true`, `npm install` will be run before Eleventy is invoked. optional
        install_dependencies: false
          
  
